name: Deploy API to Oracle Cloud

on:
  push:
    branches:
      - master # Se a sua branch principal for 'master', altere aqui.

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: 1. Checkout do Código
        uses: actions/checkout@v4

      - name: 1.5 Setup PHP e Instalação de Dependências
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3' # Altere para a versão exata do seu projeto
      
      - name: Instalando Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader --no-dev
        working-directory: ./src # Aponta para onde o seu composer.json está  

      - name: 2. Transferência Segura (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/home/ubuntu/api-producao"

      - name: 3. Orquestração Docker (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            RELEASE_DIR="/home/ubuntu/releases/${{ github.sha }}"
            CURRENT_DIR="/home/ubuntu/api-producao"

            # restore .env into the new release
            cp /home/ubuntu/.env_producao "${RELEASE_DIR}/.env"

            # atomically switch "current" to the new release
            ln -sfn "${RELEASE_DIR}" "${CURRENT_DIR}"

            cd "${CURRENT_DIR}"

            docker compose up -d
            docker compose restart

            docker exec carteira_app php artisan migrate --force
            docker image prune -af